import turtle
a = turtle.Turtle()
a.speed(0)
a.shape("turtle")
turtle.bgcolor("gray")
a.penup()
a.goto(-200,200)
a.pendown()
a.color("white")
a.begin_fill()
for i in range(2):
	a.forward(400)
	a.right(90)
	a.forward(260)
	a.right(90)
a.end_fill()
a.goto(0,10)
a.color("red")
a.begin_fill()
a.circle(60)
a.end_fill()
a.penup()
a.goto(-300,300)
a.pendown()
turtle.done()