import turtle
a = turtle.Turtle()
a.shape("turtle")
a.speed(0)
turtle.bgcolor("gray")
a.penup()
a.goto(-200,200)
a.pendown()
a.begin_fill()
for i in range(2):
	a.color("blue")
	a.fd(134)
	a.rt(90)
	a.fd(260)
	a.rt(90)
a.end_fill()
a.fd(134)
a.begin_fill()
for i in range(2):
	a.color("white")
	a.fd(134)
	a.rt(90)
	a.fd(260)
	a.rt(90)
a.end_fill()
a.fd(134)
a.begin_fill()
for i in range(2):
	a.color("red")
	a.fd(134)
	a.rt(90)
	a.fd(260)
	a.rt(90)
a.end_fill()
a.penup()
a.goto(-300,300)
a.pendown()
turtle.done()